var UI
var BBCodes
var ScriptAPI
var Premium
var Quests
var Quest
var QuestArrows
var VillageContext
var Favicon
var WorldSwitch
var TribalWars
var Village
var Resources
var Format
var Dialog
var DialogQueue
var VillageGroups
var VillageGroupMenu
var OrderProgress
var Timing
var HotKeys
var Connection
var Command
var Toggler
var STracking
var BuildFeatureAvailability
var QuickBar
var UnitPopup
var Place
var GuestRegister
var BotProtect
var DailyBonus
var ItemUIFactory
var Visual
var VisualAnim
var CasualTransferForm
var Questlines
var RewardSystem
var Chat
var ChatLang
var ChatStorage
var ChatWindow
var ChatContacts
var ChatConversation
var GroupChat